CREATE DATABASE ROAD_ACCIDENT;

USE ROAD_ACCIDENT;

CREATE TABLE ACCIDENT_RAW (ID VARCHAR(20) PRIMARY KEY,SEVERITY INT,
START_TIME DATETIME,END_TIME DATETIME,START_LAT DECIMAL(8,5),
START_LNG DECIMAL(8,5),DISTANCE DECIMAL(8,5),STREET VARCHAR(50),
CITY VARCHAR(50),COUNTRY VARCHAR(50),STATE VARCHAR(50),TEMPERATURE DECIMAL(5,2),
HUMIDITY DECIMAL(5,2),VISIBILITY DECIMAL(5,2),WIND_SPEED DECIMAL(5,2),
WEATHER_CONDITION VARCHAR(100),CROSSING BOOLEAN,JUNCTION BOOLEAN,
STOP BOOLEAN,TRAFFIC_SIGNAL BOOLEAN,SUNRISE_SUNSET VARCHAR(50));

SELECT* FROM ACCIDENT_RAW;


LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Road_Accident.csv'
INTO TABLE Accident_RAW
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT* FROM ACCIDENT_RAW LIMIT 5;

CREATE TABLE ACCIDENT (ID VARCHAR(50) PRIMARY KEY,SEVERITY INT,
START_TIME DATETIME,END_TIME DATETIME,DISTANCE DECIMAL(10,2));

CREATE TABLE LOCATION (ID VARCHAR(50) PRIMARY KEY,START_LAT DECIMAL(10,6),
START_LNG DECIMAL(10,6),STREET VARCHAR(255),CITY VARCHAR(100),
DISTRICT VARCHAR(100),STATE VARCHAR(100),
FOREIGN KEY (ID)REFERENCES ACCIDENT(ID));
    
CREATE TABLE WEATHER (ID VARCHAR(50) PRIMARY KEY,TEMPERATURE DECIMAL(5,2),
HUMIDITY DECIMAL(5,2),VISIBILITY DECIMAL(5,2),WIND_SPEED DECIMAL(5,2),
WEATHER_CONDITION VARCHAR(100),SUNRISE_SUNSET VARCHAR(50),
FOREIGN KEY (ID)REFERENCES ACCIDENT(ID));
    
CREATE TABLE ROAD_FEATURES (ID VARCHAR(50) PRIMARY KEY,CROSSING BOOL,
JUNCTION BOOL,STOP BOOL,TRAFFIC_SIGNAL BOOL,
FOREIGN KEY (ID)REFERENCES ACCIDENT(ID));
    
INSERT INTO ACCIDENT
(ID, SEVERITY, START_TIME, END_TIME, DISTANCE)
SELECT ID, SEVERITY, START_TIME, END_TIME, DISTANCE
FROM ACCIDENT_RAW;

INSERT INTO LOCATION
(ID, START_LAT, START_LNG, STREET, CITY, DISTRICT, STATE)
SELECT ID, START_LAT, START_LNG, STREET, CITY, COUNTRY, STATE
FROM ACCIDENT_RAW;
    
INSERT INTO WEATHER(ID,TEMPERATURE,HUMIDITY,VISIBILITY,
WIND_SPEED,WEATHER_CONDITION,SUNRISE_SUNSET)
SELECT ID,TEMPERATURE,HUMIDITY,VISIBILITY,
WIND_SPEED,WEATHER_CONDITION,SUNRISE_SUNSET
FROM ACCIDENT_RAW;

INSERT INTO ROAD_FEATURES
(ID, CROSSING, JUNCTION, STOP, TRAFFIC_SIGNAL)
SELECT ID, CROSSING, JUNCTION, STOP, TRAFFIC_SIGNAL
FROM ACCIDENT_RAW;

## Top 5 City Wise Accident Count
SELECT L.CITY, COUNT(A.ID) AS ACCIDENT_COUNT FROM ACCIDENT A INNER JOIN LOCATION L 
ON A.ID= L.ID GROUP BY L.CITY ORDER BY COUNT(A.ID) DESC LIMIT 5;

## Top 5 States with Highest Accident Count and Average Severity
SELECT L.STATE, AVG(A.SEVERITY) AS AVG_SEVERITY, COUNT(A.ID) AS ACCIDENT_COUNT 
FROM ACCIDENT A INNER JOIN LOCATION L ON A.ID= L.ID
GROUP BY L.STATE ORDER BY ACCIDENT_COUNT DESC LIMIT 5;


## Top 5 Weather Conditions with Highest Accident Count and Average Severity
SELECT W.WEATHER_CONDITION, COUNT(A.ID) AS ACCIDENT_COUNT, AVG(SEVERITY) AS AVG_SEVERITY 
FROM WEATHER W INNER JOIN ACCIDENT A ON W.ID=A.ID GROUP BY WEATHER_CONDITION ORDER BY 
ACCIDENT_COUNT DESC LIMIT 5;

## Top 5 High-Risk City and Weather Condition Combinations by Accident Count
SELECT L.CITY, W.WEATHER_CONDITION, W.SUNRISE_SUNSET, AVG(A.SEVERITY) AS AVG_SEVERITY ,
COUNT(A.ID) AS HIGH_ACCIDENTS  FROM ACCIDENT A INNER JOIN LOCATION L ON A.ID=L.ID
INNER JOIN WEATHER W ON A.ID=W.ID GROUP BY L.CITY,W.WEATHER_CONDITION ,
W.SUNRISE_SUNSET ORDER BY HIGH_ACCIDENTS DESC LIMIT 5;

## Top 10 High-Risk Districts with High Humidity and Low Visibility Conditions
SELECT L.DISTRICT, W.HUMIDITY, W.VISIBILITY, COUNT(A.ID) AS HIGH_ACCIDENT
FROM ACCIDENT A INNER JOIN LOCATION L ON A.ID=L.ID INNER JOIN WEATHER W 
ON A.ID=W.ID WHERE W.HUMIDITY > 70 AND W.VISIBILITY < 5 GROUP BY
L.DISTRICT, W.HUMIDITY, W.VISIBILITY ORDER BY HIGH_ACCIDENT DESC LIMIT 10;






    